#!/bin/sh
SCRIPT_DIR=$(dirname "$(readlink "$0")")

if [ -f $SCRIPT_DIR/falanx-args.txt ] ; then
    rm $SCRIPT_DIR/falanx-args.txt
fi

for ARG in "$@"
do
    echo $ARG >> $SCRIPT_DIR/falanx-args.txt
done
