// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemLevelOrderHistory.proto

public final class ItemLevelOrderHistoryOuterClass {
  private ItemLevelOrderHistoryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ItemLevelOrderHistoryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ItemLevelOrderHistory)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string client_id = 1;</code>
     */
    java.lang.String getClientId();
    /**
     * <code>string client_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>string retail_sku_id = 2;</code>
     */
    java.lang.String getRetailSkuId();
    /**
     * <code>string retail_sku_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getRetailSkuIdBytes();

    /**
     * <code>double category_id = 3;</code>
     */
    double getCategoryId();

    /**
     * <code>string brand = 4;</code>
     */
    java.lang.String getBrand();
    /**
     * <code>string brand = 4;</code>
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>string product = 5;</code>
     */
    java.lang.String getProduct();
    /**
     * <code>string product = 5;</code>
     */
    com.google.protobuf.ByteString
        getProductBytes();

    /**
     * <code>float order_tss = 6;</code>
     */
    float getOrderTss();
  }
  /**
   * Protobuf type {@code ItemLevelOrderHistory}
   */
  public  static final class ItemLevelOrderHistory extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ItemLevelOrderHistory)
      ItemLevelOrderHistoryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ItemLevelOrderHistory.newBuilder() to construct.
    private ItemLevelOrderHistory(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ItemLevelOrderHistory() {
      clientId_ = "";
      retailSkuId_ = "";
      categoryId_ = 0D;
      brand_ = "";
      product_ = "";
      orderTss_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ItemLevelOrderHistory(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              retailSkuId_ = s;
              break;
            }
            case 25: {

              categoryId_ = input.readDouble();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              brand_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              product_ = s;
              break;
            }
            case 53: {

              orderTss_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ItemLevelOrderHistoryOuterClass.internal_static_ItemLevelOrderHistory_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ItemLevelOrderHistoryOuterClass.internal_static_ItemLevelOrderHistory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory.class, ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory.Builder.class);
    }

    public static final int CLIENT_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object clientId_;
    /**
     * <code>string client_id = 1;</code>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>string client_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RETAIL_SKU_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object retailSkuId_;
    /**
     * <code>string retail_sku_id = 2;</code>
     */
    public java.lang.String getRetailSkuId() {
      java.lang.Object ref = retailSkuId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        retailSkuId_ = s;
        return s;
      }
    }
    /**
     * <code>string retail_sku_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRetailSkuIdBytes() {
      java.lang.Object ref = retailSkuId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retailSkuId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATEGORY_ID_FIELD_NUMBER = 3;
    private double categoryId_;
    /**
     * <code>double category_id = 3;</code>
     */
    public double getCategoryId() {
      return categoryId_;
    }

    public static final int BRAND_FIELD_NUMBER = 4;
    private volatile java.lang.Object brand_;
    /**
     * <code>string brand = 4;</code>
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      }
    }
    /**
     * <code>string brand = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCT_FIELD_NUMBER = 5;
    private volatile java.lang.Object product_;
    /**
     * <code>string product = 5;</code>
     */
    public java.lang.String getProduct() {
      java.lang.Object ref = product_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        product_ = s;
        return s;
      }
    }
    /**
     * <code>string product = 5;</code>
     */
    public com.google.protobuf.ByteString
        getProductBytes() {
      java.lang.Object ref = product_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        product_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDER_TSS_FIELD_NUMBER = 6;
    private float orderTss_;
    /**
     * <code>float order_tss = 6;</code>
     */
    public float getOrderTss() {
      return orderTss_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
      }
      if (!getRetailSkuIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, retailSkuId_);
      }
      if (categoryId_ != 0D) {
        output.writeDouble(3, categoryId_);
      }
      if (!getBrandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, brand_);
      }
      if (!getProductBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, product_);
      }
      if (orderTss_ != 0F) {
        output.writeFloat(6, orderTss_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
      }
      if (!getRetailSkuIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, retailSkuId_);
      }
      if (categoryId_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, categoryId_);
      }
      if (!getBrandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, brand_);
      }
      if (!getProductBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, product_);
      }
      if (orderTss_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, orderTss_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory)) {
        return super.equals(obj);
      }
      ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory other = (ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory) obj;

      boolean result = true;
      result = result && getClientId()
          .equals(other.getClientId());
      result = result && getRetailSkuId()
          .equals(other.getRetailSkuId());
      result = result && (
          java.lang.Double.doubleToLongBits(getCategoryId())
          == java.lang.Double.doubleToLongBits(
              other.getCategoryId()));
      result = result && getBrand()
          .equals(other.getBrand());
      result = result && getProduct()
          .equals(other.getProduct());
      result = result && (
          java.lang.Float.floatToIntBits(getOrderTss())
          == java.lang.Float.floatToIntBits(
              other.getOrderTss()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + RETAIL_SKU_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRetailSkuId().hashCode();
      hash = (37 * hash) + CATEGORY_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getCategoryId()));
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
      hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
      hash = (53 * hash) + getProduct().hashCode();
      hash = (37 * hash) + ORDER_TSS_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getOrderTss());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ItemLevelOrderHistory}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ItemLevelOrderHistory)
        ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ItemLevelOrderHistoryOuterClass.internal_static_ItemLevelOrderHistory_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ItemLevelOrderHistoryOuterClass.internal_static_ItemLevelOrderHistory_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory.class, ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory.Builder.class);
      }

      // Construct using ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        clientId_ = "";

        retailSkuId_ = "";

        categoryId_ = 0D;

        brand_ = "";

        product_ = "";

        orderTss_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ItemLevelOrderHistoryOuterClass.internal_static_ItemLevelOrderHistory_descriptor;
      }

      @java.lang.Override
      public ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory getDefaultInstanceForType() {
        return ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory.getDefaultInstance();
      }

      @java.lang.Override
      public ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory build() {
        ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory buildPartial() {
        ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory result = new ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory(this);
        result.clientId_ = clientId_;
        result.retailSkuId_ = retailSkuId_;
        result.categoryId_ = categoryId_;
        result.brand_ = brand_;
        result.product_ = product_;
        result.orderTss_ = orderTss_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory) {
          return mergeFrom((ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory other) {
        if (other == ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory.getDefaultInstance()) return this;
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getRetailSkuId().isEmpty()) {
          retailSkuId_ = other.retailSkuId_;
          onChanged();
        }
        if (other.getCategoryId() != 0D) {
          setCategoryId(other.getCategoryId());
        }
        if (!other.getBrand().isEmpty()) {
          brand_ = other.brand_;
          onChanged();
        }
        if (!other.getProduct().isEmpty()) {
          product_ = other.product_;
          onChanged();
        }
        if (other.getOrderTss() != 0F) {
          setOrderTss(other.getOrderTss());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object clientId_ = "";
      /**
       * <code>string client_id = 1;</code>
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_id = 1;</code>
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_id = 1;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>string client_id = 1;</code>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object retailSkuId_ = "";
      /**
       * <code>string retail_sku_id = 2;</code>
       */
      public java.lang.String getRetailSkuId() {
        java.lang.Object ref = retailSkuId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          retailSkuId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string retail_sku_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRetailSkuIdBytes() {
        java.lang.Object ref = retailSkuId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          retailSkuId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string retail_sku_id = 2;</code>
       */
      public Builder setRetailSkuId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        retailSkuId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string retail_sku_id = 2;</code>
       */
      public Builder clearRetailSkuId() {
        
        retailSkuId_ = getDefaultInstance().getRetailSkuId();
        onChanged();
        return this;
      }
      /**
       * <code>string retail_sku_id = 2;</code>
       */
      public Builder setRetailSkuIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        retailSkuId_ = value;
        onChanged();
        return this;
      }

      private double categoryId_ ;
      /**
       * <code>double category_id = 3;</code>
       */
      public double getCategoryId() {
        return categoryId_;
      }
      /**
       * <code>double category_id = 3;</code>
       */
      public Builder setCategoryId(double value) {
        
        categoryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double category_id = 3;</code>
       */
      public Builder clearCategoryId() {
        
        categoryId_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object brand_ = "";
      /**
       * <code>string brand = 4;</code>
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          brand_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string brand = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string brand = 4;</code>
       */
      public Builder setBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 4;</code>
       */
      public Builder clearBrand() {
        
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 4;</code>
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        brand_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object product_ = "";
      /**
       * <code>string product = 5;</code>
       */
      public java.lang.String getProduct() {
        java.lang.Object ref = product_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          product_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string product = 5;</code>
       */
      public com.google.protobuf.ByteString
          getProductBytes() {
        java.lang.Object ref = product_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          product_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string product = 5;</code>
       */
      public Builder setProduct(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        product_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string product = 5;</code>
       */
      public Builder clearProduct() {
        
        product_ = getDefaultInstance().getProduct();
        onChanged();
        return this;
      }
      /**
       * <code>string product = 5;</code>
       */
      public Builder setProductBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        product_ = value;
        onChanged();
        return this;
      }

      private float orderTss_ ;
      /**
       * <code>float order_tss = 6;</code>
       */
      public float getOrderTss() {
        return orderTss_;
      }
      /**
       * <code>float order_tss = 6;</code>
       */
      public Builder setOrderTss(float value) {
        
        orderTss_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float order_tss = 6;</code>
       */
      public Builder clearOrderTss() {
        
        orderTss_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ItemLevelOrderHistory)
    }

    // @@protoc_insertion_point(class_scope:ItemLevelOrderHistory)
    private static final ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory();
    }

    public static ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ItemLevelOrderHistory>
        PARSER = new com.google.protobuf.AbstractParser<ItemLevelOrderHistory>() {
      @java.lang.Override
      public ItemLevelOrderHistory parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemLevelOrderHistory(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ItemLevelOrderHistory> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ItemLevelOrderHistory> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ItemLevelOrderHistoryOuterClass.ItemLevelOrderHistory getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ItemLevelOrderHistory_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ItemLevelOrderHistory_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033ItemLevelOrderHistory.proto\"\211\001\n\025ItemLe" +
      "velOrderHistory\022\021\n\tclient_id\030\001 \001(\t\022\025\n\rre" +
      "tail_sku_id\030\002 \001(\t\022\023\n\013category_id\030\003 \001(\001\022\r" +
      "\n\005brand\030\004 \001(\t\022\017\n\007product\030\005 \001(\t\022\021\n\torder_" +
      "tss\030\006 \001(\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ItemLevelOrderHistory_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ItemLevelOrderHistory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ItemLevelOrderHistory_descriptor,
        new java.lang.String[] { "ClientId", "RetailSkuId", "CategoryId", "Brand", "Product", "OrderTss", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
